/** @vitest-environment jsdom */
import '@testing-library/jest-dom';
import { describe, test, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor, within, act } from '@testing-library/react';

// Mock the WASM module so this suite doesn't require a built pkg/ (which is
// gitignored and generated by `npm run prepare-wasm`).  The mock simulates
// the Sender Keys group-crypto contract that the real WASM binding provides:
//   - group_encrypt records the current member set at encryption time
//   - group_decrypt succeeds only if the decrypting member was in the group
//     at the time the ciphertext was created (forward secrecy after removal)
//   - group_add_member / group_remove_member return NEW GroupHandle instances
//     (never mutate the input), matching the real binding's contract
vi.mock('../../../core/bindings/wasm/pkg/index.js', () => {
    const arrayEquals = (a: Uint8Array, b: Uint8Array) =>
        a.length === b.length && a.every((v, i) => v === b[i]);

    class IdentityHandle {
        publicBytes: Uint8Array;
        constructor(publicBytes: Uint8Array) { this.publicBytes = publicBytes; }
        public_bytes() { return this.publicBytes; }
    }

    class GroupHandle {
        members: Uint8Array[];
        constructor(members: Uint8Array[] = []) { this.members = members; }
    }

    // Map each ciphertext to the member set that was present at encryption
    // time, so group_decrypt can enforce forward secrecy after removal. Keyed
    // by the ciphertext's bytes (not object identity) because the component
    // hands a fresh copy to sendEnvelope, and tests decrypt that delivered copy.
    const encryptionMembers = new Map<string, Uint8Array[]>();
    const ciphertextKey = (ciphertext: Uint8Array) => Array.from(ciphertext).join(',');

    function generate_identity() {
        const bytes = new Uint8Array(32);
        crypto.getRandomValues(bytes);
        return new IdentityHandle(bytes);
    }

    function group_create(selfIdentity: IdentityHandle) {
        return new GroupHandle([selfIdentity.public_bytes()]);
    }

    function group_add_member(group: GroupHandle, publicBytes: Uint8Array) {
        if (group.members.some((b) => arrayEquals(b, publicBytes))) {
            return new GroupHandle([...group.members]);
        }
        return new GroupHandle([...group.members, publicBytes]);
    }

    function group_remove_member(group: GroupHandle, publicBytes: Uint8Array) {
        return new GroupHandle(group.members.filter((b) => !arrayEquals(b, publicBytes)));
    }

    function group_encrypt(group: GroupHandle, _senderIdentity: IdentityHandle, plaintextBytes: Uint8Array) {
        const ciphertext = new Uint8Array(plaintextBytes);
        encryptionMembers.set(ciphertextKey(ciphertext), [...group.members]);
        return ciphertext;
    }

    function group_decrypt(_group: GroupHandle, memberIdentity: IdentityHandle, ciphertext: Uint8Array) {
        const memberSet = encryptionMembers.get(ciphertextKey(ciphertext));
        if (!memberSet) throw new Error('decryption failed');
        const publicKey = memberIdentity.public_bytes();
        if (!memberSet.some((b) => arrayEquals(b, publicKey))) {
            throw new Error('decryption failed');
        }
        return ciphertext;
    }

    function derive_safety_number(_localKey: Uint8Array, _remoteKey: Uint8Array) {
        return '00000 00000';
    }

    // GRP-4: group state persistence bindings, mirroring the real wasm
    // exports. Serialization is a pure function of the handle's current
    // member set (never cached, never mutating the handle), and
    // group_from_bytes validates the blob and returns a live GroupHandle
    // from this same factory, so the restored group is immediately usable.
    const GROUP_BLOB_MAGIC = [0x47, 0x52, 0x50, 0x34]; // "GRP4"
    const GROUP_BLOB_VERSION = 0x01;

    function group_to_bytes(group: GroupHandle): Uint8Array {
        const bytes: number[] = [...GROUP_BLOB_MAGIC, GROUP_BLOB_VERSION];
        const pushU32 = (value: number) => {
            bytes.push((value >>> 24) & 0xff, (value >>> 16) & 0xff, (value >>> 8) & 0xff, value & 0xff);
        };
        pushU32(group.members.length);
        for (const member of group.members) {
            pushU32(member.length);
            bytes.push(...member);
        }
        return new Uint8Array(bytes);
    }

    function group_from_bytes(blob: Uint8Array): GroupHandle {
        const readU32 = (offset: number) =>
            ((blob[offset] << 24) | (blob[offset + 1] << 16) | (blob[offset + 2] << 8) | blob[offset + 3]) >>> 0;
        if (!(blob instanceof Uint8Array) || blob.length < 9) {
            throw new Error('group_from_bytes: malformed group blob');
        }
        for (let i = 0; i < GROUP_BLOB_MAGIC.length; i++) {
            if (blob[i] !== GROUP_BLOB_MAGIC[i]) {
                throw new Error('group_from_bytes: malformed group blob');
            }
        }
        if (blob[4] !== GROUP_BLOB_VERSION) {
            throw new Error('group_from_bytes: unsupported group blob version');
        }
        const memberCount = readU32(5);
        const members: Uint8Array[] = [];
        let offset = 9;
        for (let i = 0; i < memberCount; i++) {
            if (offset + 4 > blob.length) {
                throw new Error('group_from_bytes: malformed group blob');
            }
            const memberLength = readU32(offset);
            offset += 4;
            if (offset + memberLength > blob.length) {
                throw new Error('group_from_bytes: malformed group blob');
            }
            members.push(blob.slice(offset, offset + memberLength));
            offset += memberLength;
        }
        if (offset !== blob.length) {
            throw new Error('group_from_bytes: malformed group blob');
        }
        return new GroupHandle(members);
    }

    // The real binding extracts the identity key from a prekey bundle. In these
    // tests lookupPrekey returns the identity key bytes directly (no bundle
    // envelope), so this is an identity passthrough — matching
    // group_real_peer.test.tsx.
    function bundle_identity_key_bytes(bundle: Uint8Array) { return bundle; }

    return {
        generate_identity,
        group_create,
        group_add_member,
        group_remove_member,
        group_encrypt,
        group_decrypt,
        derive_safety_number,
        group_to_bytes,
        group_from_bytes,
        bundle_identity_key_bytes,
        IdentityHandle,
        GroupHandle,
    };
});
vi.mock('../src/wasm_init', () => ({ ensureWasmInit: async () => {} }));

// ── Storage mock ───────────────────────────────────────────────────────────
//
// Mirrors the real StorageGate API (get/put) with an in-memory store that
// simulates persistence across a "reload" (re-render with a fresh component
// instance) — the same pattern as group_real_peer.test.tsx.

vi.mock('../src/storage', () => {
    const store = new Map<string, unknown>();

    class MockStorageGate {
        async open() { return Promise.resolve(); }
        async get(_store: string, id: string) {
            return store.get(id) ?? null;
        }
        async put(_store: string, id: string, value: unknown) {
            store.set(id, value);
        }
    }
    // Expose the store so tests can reset it between runs.
    (MockStorageGate as unknown as { __store: Map<string, unknown> }).__store = store;
    return { StorageGate: MockStorageGate };
});

import { StorageGate as MockStorageGate } from '../src/storage';
import { GroupConversation } from '../src/GroupConversation';
import {
    generate_identity,
    group_create,
    group_decrypt,
} from '../../../core/bindings/wasm/pkg/index.js';

// ── Fixtures ───────────────────────────────────────────────────────────────
//
// The group view no longer ships demo members: every member is a real peer
// added by recipient ID, whose public key is looked up from the relay. These
// fixtures therefore drive the same scenarios the demo scaffolding used to
// cover — forward secrecy after removal and fail-closed decryption — with real
// peers instead of the retired Alice/Bob/Eve chips.

const selfIdentity = generate_identity();
const selfRecipientId = 'self-recipient-id';

// Two real peer identities. lookupPrekey returns each peer's published
// identity key, exactly as the relay would.
const peerAIdentity = generate_identity();
const peerBIdentity = generate_identity();
const peerAId = 'peer-a-recipient-id';
const peerBId = 'peer-b-recipient-id';
const peerAPublic = peerAIdentity.public_bytes();
const peerBPublic = peerBIdentity.public_bytes();

/**
 * A transport whose lookupPrekey returns the peer's identity key bytes
 * directly (the mocked `bundle_identity_key_bytes` is an identity passthrough,
 * matching group_real_peer.test.tsx). sendEnvelope records every delivery so a
 * test can inspect the ciphertext actually sent to a member; pickupEnvelope
 * reports an empty mailbox.
 */
function makeTransport() {
    const sent: Array<{ recipientId: string; envelope: Uint8Array }> = [];
    return {
        sent,
        lookupPrekey: vi.fn(async (recipientId: string): Promise<Uint8Array> => {
            if (recipientId === peerAId) return peerAPublic;
            if (recipientId === peerBId) return peerBPublic;
            throw new Error('relay: recipient not found');
        }),
        sendEnvelope: vi.fn(async (recipientId: string, envelope: Uint8Array): Promise<void> => {
            sent.push({ recipientId, envelope: new Uint8Array(envelope) });
        }),
        pickupEnvelope: vi.fn(async (): Promise<Uint8Array> => {
            throw new Error('NotFound');
        }),
    };
}

/** The most recent ciphertext delivered to `recipientId`. */
function lastEnvelopeTo(transport: ReturnType<typeof makeTransport>, recipientId: string): Uint8Array {
    const deliveries = transport.sent.filter((d) => d.recipientId === recipientId);
    expect(deliveries.length).toBeGreaterThan(0);
    return deliveries[deliveries.length - 1].envelope;
}

/**
 * Attempt to decrypt `ciphertext` as `memberIdentity`. The mocked group_decrypt
 * enforces forward secrecy from the member set recorded at encryption time, so
 * this throws for a member who was not in the group when the message was sent.
 */
function decryptAs(memberIdentity: ReturnType<typeof generate_identity>, ciphertext: Uint8Array): string {
    return new TextDecoder().decode(group_decrypt(group_create(selfIdentity), memberIdentity, ciphertext));
}

/** Add a peer by recipient ID and wait for its chip to appear. */
async function addPeer(recipientId: string) {
    fireEvent.change(screen.getByTestId('group-peer-id-input'), { target: { value: recipientId } });
    fireEvent.click(screen.getByTestId('add-peer-button'));
    await waitFor(() => expect(screen.getByTestId(`member-${recipientId}`)).toBeInTheDocument());
}

/** Render the group view with the app's real identity and a mock storage gate. */
function renderGroup(transport: ReturnType<typeof makeTransport>) {
    return render(
        <GroupConversation
            identity={selfIdentity}
            selfRecipientId={selfRecipientId}
            transport={transport}
            storageGate={new MockStorageGate({ indexedDB: undefined, keyBytes: new Uint8Array(32) })}
        />,
    );
}

// With fake timers `waitFor` hangs (its polling uses setTimeout), so the
// fail-closed test flushes microtasks + timer callbacks explicitly instead.
async function flush() {
    await act(async () => {
        await vi.advanceTimersByTimeAsync(0);
    });
}

async function tick(ms: number) {
    await act(async () => {
        await vi.advanceTimersByTimeAsync(ms);
    });
}

beforeEach(() => {
    (MockStorageGate as unknown as { __store: Map<string, unknown> }).__store.clear();
});

describe('GroupConversation', () => {
    test('the member list shows only real peers added by recipient ID — no demo members', async () => {
        const transport = makeTransport();
        renderGroup(transport);

        fireEvent.click(await screen.findByTestId('create-group-button'));
        await waitFor(() => expect(screen.getByTestId('member-list')).toBeInTheDocument());

        // The retired demo scaffolding rendered Alice/Bob/Eve chips with
        // add-Alice/add-Bob/remove-Eve controls. None of that may render.
        expect(screen.queryByTestId('add-Alice')).not.toBeInTheDocument();
        expect(screen.queryByTestId('add-Bob')).not.toBeInTheDocument();
        expect(screen.queryByTestId('add-Eve')).not.toBeInTheDocument();
        expect(screen.queryByText('Alice')).not.toBeInTheDocument();
        expect(screen.queryByText('Bob')).not.toBeInTheDocument();
        expect(screen.queryByText('Eve')).not.toBeInTheDocument();

        await addPeer(peerAId);

        // The only chip in the list is the real peer.
        const list = screen.getByTestId('member-list');
        expect(within(list).getByText(peerAId)).toBeInTheDocument();
        expect(within(list).queryByText('Alice')).not.toBeInTheDocument();
    });

    test('a real peer added by recipient ID persists across a remount', async () => {
        const transport = makeTransport();
        const first = renderGroup(transport);

        fireEvent.click(await screen.findByTestId('create-group-button'));
        await waitFor(() => expect(screen.getByTestId('member-list')).toBeInTheDocument());
        await addPeer(peerAId);

        first.unmount();

        // Remount against the same persisted storage: the real peer must come
        // back from the persistence path, and no demo member may be fabricated.
        renderGroup(makeTransport());
        await waitFor(() => expect(screen.getByTestId(`member-${peerAId}`)).toBeInTheDocument());
        expect(screen.queryByText('Alice')).not.toBeInTheDocument();
        expect(screen.queryByTestId('add-Alice')).not.toBeInTheDocument();
    });

    test('with no members the group view renders an empty state and fabricates no members', async () => {
        const transport = makeTransport();
        renderGroup(transport);

        fireEvent.click(await screen.findByTestId('create-group-button'));
        await waitFor(() => expect(screen.getByTestId('member-list')).toBeInTheDocument());

        // No chips at all — the mount effect must not fabricate demo members.
        expect(screen.getByTestId('member-list').querySelectorAll('.member-chip').length).toBe(0);
        expect(screen.queryByText('Alice')).not.toBeInTheDocument();
        expect(screen.queryByText('Bob')).not.toBeInTheDocument();
        expect(screen.queryByText('Eve')).not.toBeInTheDocument();

        // An explicit empty state is rendered instead.
        expect(screen.getByTestId('member-list-empty')).toBeInTheDocument();
    });

    test('a removed real peer cannot decrypt a message sent after their removal', async () => {
        const transport = makeTransport();
        renderGroup(transport);

        fireEvent.click(await screen.findByTestId('create-group-button'));
        await waitFor(() => expect(screen.getByTestId('member-list')).toBeInTheDocument());

        await addPeer(peerAId);
        await addPeer(peerBId);

        // Both peers are members: a message sent now is decryptable by peer A.
        fireEvent.change(screen.getByTestId('group-message-input'), { target: { value: 'peer A is still here' } });
        fireEvent.click(screen.getByTestId('group-send-button'));
        await waitFor(() => expect(screen.getByText('peer A is still here')).toBeInTheDocument());
        const beforeRemoval = lastEnvelopeTo(transport, peerBId);
        expect(decryptAs(peerAIdentity, beforeRemoval)).toBe('peer A is still here');

        // Remove peer A. group_remove_member rotates the sender key (see
        // core/protocol's member_removal_rotation.rs), so this is a real
        // forward-secrecy check, not a simulated one.
        fireEvent.click(screen.getByTestId(`remove-peer-${peerAId}`));
        await waitFor(() => expect(screen.getByTestId(`add-peer-${peerAId}`)).toBeInTheDocument());

        fireEvent.change(screen.getByTestId('group-message-input'), { target: { value: 'peer A is gone now' } });
        fireEvent.click(screen.getByTestId('group-send-button'));
        await waitFor(() => expect(screen.getByText('peer A is gone now')).toBeInTheDocument());
        const afterRemoval = lastEnvelopeTo(transport, peerBId);

        // Peer A's decrypt attempt against the post-removal message genuinely fails.
        expect(() => decryptAs(peerAIdentity, afterRemoval)).toThrow();
        // Peer B, still a member, still decrypts it fine.
        expect(decryptAs(peerBIdentity, afterRemoval)).toBe('peer A is gone now');
    });

    test('a received envelope that fails to decrypt fails closed — no plaintext, a visible warning', async () => {
        vi.useFakeTimers();
        try {
            const transport = makeTransport();
            // The relay hands the local user an envelope the crypto layer cannot
            // decrypt (it was never produced by group_encrypt).
            transport.pickupEnvelope.mockImplementation(async () => new Uint8Array([9, 9, 9, 9, 9, 9, 9, 9]));

            renderGroup(transport);
            await flush();
            fireEvent.click(screen.getByTestId('create-group-button'));
            await flush();
            expect(screen.getByTestId('member-list')).toBeInTheDocument();

            // Advance past one poll interval so the receive loop picks it up.
            await tick(5000);

            // Fail closed: the undecryptable envelope is discarded, never
            // rendered as plaintext, and a visible warning is surfaced.
            // Assert no message node rendered at all — a "not the digits" text
            // check would be vacuous, since the raw bytes decode to control
            // characters and could never match the literal.
            expect(screen.queryAllByTestId(/^message-/)).toHaveLength(0);
            const warning = screen.getByRole('alert');
            expect(warning.textContent).toMatch(/could not be verified|discarded/i);
        } finally {
            vi.useRealTimers();
        }
    });
});
