/** @vitest-environment jsdom */
import '@testing-library/jest-dom';
import { describe, test, expect } from 'vitest';
import { render, screen, fireEvent, waitFor, within } from '@testing-library/react';

// Mock the WASM module so this suite doesn't require a built pkg/ (which is
// gitignored and generated by `npm run prepare-wasm`).  The mock simulates
// the Sender Keys group-crypto contract that the real WASM binding provides:
//   - group_encrypt records the current member set at encryption time
//   - group_decrypt succeeds only if the decrypting member was in the group
//     at the time the ciphertext was created (forward secrecy after removal)
//   - group_add_member / group_remove_member return NEW GroupHandle instances
//     (never mutate the input), matching the real binding's contract
vi.mock('../../../core/bindings/wasm/pkg/index.js', () => {
    const arrayEquals = (a: Uint8Array, b: Uint8Array) =>
        a.length === b.length && a.every((v, i) => v === b[i]);

    class IdentityHandle {
        publicBytes: Uint8Array;
        constructor(publicBytes: Uint8Array) { this.publicBytes = publicBytes; }
        public_bytes() { return this.publicBytes; }
    }

    class GroupHandle {
        members: Uint8Array[];
        constructor(members: Uint8Array[] = []) { this.members = members; }
    }

    // Map each ciphertext to the member set that was present at encryption
    // time, so group_decrypt can enforce forward secrecy after removal.
    const encryptionMembers = new Map<Uint8Array, Uint8Array[]>();

    function generate_identity() {
        const bytes = new Uint8Array(32);
        crypto.getRandomValues(bytes);
        return new IdentityHandle(bytes);
    }

    function group_create(selfIdentity: IdentityHandle) {
        return new GroupHandle([selfIdentity.public_bytes()]);
    }

    function group_add_member(group: GroupHandle, publicBytes: Uint8Array) {
        if (group.members.some((b) => arrayEquals(b, publicBytes))) {
            return new GroupHandle([...group.members]);
        }
        return new GroupHandle([...group.members, publicBytes]);
    }

    function group_remove_member(group: GroupHandle, publicBytes: Uint8Array) {
        return new GroupHandle(group.members.filter((b) => !arrayEquals(b, publicBytes)));
    }

    function group_encrypt(group: GroupHandle, _senderIdentity: IdentityHandle, plaintextBytes: Uint8Array) {
        const ciphertext = new Uint8Array(plaintextBytes);
        encryptionMembers.set(ciphertext, [...group.members]);
        return ciphertext;
    }

    function group_decrypt(_group: GroupHandle, memberIdentity: IdentityHandle, ciphertext: Uint8Array) {
        const memberSet = encryptionMembers.get(ciphertext);
        if (!memberSet) throw new Error('decryption failed');
        const publicKey = memberIdentity.public_bytes();
        if (!memberSet.some((b) => arrayEquals(b, publicKey))) {
            throw new Error('decryption failed');
        }
        return ciphertext;
    }

    function derive_safety_number(_localKey: Uint8Array, _remoteKey: Uint8Array) {
        return '00000 00000';
    }

    // GRP-4: group state persistence bindings, mirroring the real wasm
    // exports. Serialization is a pure function of the handle's current
    // member set (never cached, never mutating the handle), and
    // group_from_bytes validates the blob and returns a live GroupHandle
    // from this same factory, so the restored group is immediately usable.
    const GROUP_BLOB_MAGIC = [0x47, 0x52, 0x50, 0x34]; // "GRP4"
    const GROUP_BLOB_VERSION = 0x01;

    function group_to_bytes(group: GroupHandle): Uint8Array {
        const bytes: number[] = [...GROUP_BLOB_MAGIC, GROUP_BLOB_VERSION];
        const pushU32 = (value: number) => {
            bytes.push((value >>> 24) & 0xff, (value >>> 16) & 0xff, (value >>> 8) & 0xff, value & 0xff);
        };
        pushU32(group.members.length);
        for (const member of group.members) {
            pushU32(member.length);
            bytes.push(...member);
        }
        return new Uint8Array(bytes);
    }

    function group_from_bytes(blob: Uint8Array): GroupHandle {
        const readU32 = (offset: number) =>
            ((blob[offset] << 24) | (blob[offset + 1] << 16) | (blob[offset + 2] << 8) | blob[offset + 3]) >>> 0;
        if (!(blob instanceof Uint8Array) || blob.length < 9) {
            throw new Error('group_from_bytes: malformed group blob');
        }
        for (let i = 0; i < GROUP_BLOB_MAGIC.length; i++) {
            if (blob[i] !== GROUP_BLOB_MAGIC[i]) {
                throw new Error('group_from_bytes: malformed group blob');
            }
        }
        if (blob[4] !== GROUP_BLOB_VERSION) {
            throw new Error('group_from_bytes: unsupported group blob version');
        }
        const memberCount = readU32(5);
        const members: Uint8Array[] = [];
        let offset = 9;
        for (let i = 0; i < memberCount; i++) {
            if (offset + 4 > blob.length) {
                throw new Error('group_from_bytes: malformed group blob');
            }
            const memberLength = readU32(offset);
            offset += 4;
            if (offset + memberLength > blob.length) {
                throw new Error('group_from_bytes: malformed group blob');
            }
            members.push(blob.slice(offset, offset + memberLength));
            offset += memberLength;
        }
        if (offset !== blob.length) {
            throw new Error('group_from_bytes: malformed group blob');
        }
        return new GroupHandle(members);
    }

    return {
        generate_identity,
        group_create,
        group_add_member,
        group_remove_member,
        group_encrypt,
        group_decrypt,
        derive_safety_number,
        group_to_bytes,
        group_from_bytes,
        IdentityHandle,
        GroupHandle,
    };
});
vi.mock('../src/wasm_init', () => ({ ensureWasmInit: async () => {} }));

import { GroupConversation } from '../src/GroupConversation';
import { generate_identity } from '../../../core/bindings/wasm/pkg/index.js';

// Criterion 3: the group view fails closed without an identity + recipient ID,
// so these render sites supply the app's real identity and a no-op transport.
// The demo-member flow under test never touches the relay, so the transport
// only has to satisfy the interface (an empty mailbox rejects with "NotFound",
// which the receive loop treats as a normal empty poll).
const selfIdentity = generate_identity();
const selfRecipientId = 'self-recipient-id';
const noopTransport = {
    lookupPrekey: async () => { throw new Error('NotFound'); },
    sendEnvelope: async () => {},
    pickupEnvelope: async () => { throw new Error('NotFound'); },
};

describe('GroupConversation', () => {
    test('creates a group, adds members, and sends a message all current members decrypt', async () => {
        render(<GroupConversation identity={selfIdentity} selfRecipientId={selfRecipientId} transport={noopTransport} />);

        const createBtn = await screen.findByTestId('create-group-button');
        fireEvent.click(createBtn);

        await waitFor(() => expect(screen.getByTestId('member-list')).toBeInTheDocument());

        fireEvent.click(screen.getByTestId('add-Alice'));
        fireEvent.click(screen.getByTestId('add-Bob'));

        // Added members show a Remove button in place of Add.
        expect(screen.getByTestId('remove-Alice')).toBeInTheDocument();
        expect(screen.getByTestId('remove-Bob')).toBeInTheDocument();

        fireEvent.change(screen.getByTestId('group-message-input'), { target: { value: 'hello group' } });
        fireEvent.click(screen.getByTestId('group-send-button'));

        await waitFor(() => expect(screen.getByText('hello group')).toBeInTheDocument());

        // Both added members decrypted the real ciphertext; Eve (never added) did not.
        expect(screen.getByText(/Alice: decrypted/)).toBeInTheDocument();
        expect(screen.getByText(/Bob: decrypted/)).toBeInTheDocument();
        expect(screen.getByText(/Eve: failed/)).toBeInTheDocument();
    });

    test('a removed member cannot decrypt a message sent after their removal', async () => {
        render(<GroupConversation identity={selfIdentity} selfRecipientId={selfRecipientId} transport={noopTransport} />);

        fireEvent.click(await screen.findByTestId('create-group-button'));
        await waitFor(() => expect(screen.getByTestId('member-list')).toBeInTheDocument());

        fireEvent.click(screen.getByTestId('add-Alice'));
        fireEvent.click(screen.getByTestId('add-Eve'));

        // Eve is a member and can decrypt a message sent while she's still in the group.
        fireEvent.change(screen.getByTestId('group-message-input'), { target: { value: 'eve is still here' } });
        fireEvent.click(screen.getByTestId('group-send-button'));
        await waitFor(() => expect(screen.getByText('eve is still here')).toBeInTheDocument());
        const firstMessage = screen.getByText('eve is still here').closest('div')!;
        expect(within(firstMessage).getByText(/Eve: decrypted/)).toBeInTheDocument();

        // Remove Eve, then send a new message - her removal rotates the sender
        // key (see core/protocol's member_removal_rotation.rs), so this is a
        // real forward-secrecy check, not a simulated one.
        fireEvent.click(screen.getByTestId('remove-Eve'));
        expect(screen.getByTestId('add-Eve')).toBeInTheDocument(); // Add button reappears

        fireEvent.change(screen.getByTestId('group-message-input'), { target: { value: 'eve is gone now' } });
        fireEvent.click(screen.getByTestId('group-send-button'));

        await waitFor(() => expect(screen.getByText('eve is gone now')).toBeInTheDocument());
        const secondMessage = screen.getByText('eve is gone now').closest('div')!;

        // Eve's decrypt attempt against the post-removal message genuinely fails.
        expect(within(secondMessage).getByText(/Eve: failed/)).toBeInTheDocument();
        // Alice, still a member, still decrypts it fine.
        expect(within(secondMessage).getByText(/Alice: decrypted/)).toBeInTheDocument();
    });
});
